yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'


urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/users/urls.py
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView,
    PasswordChangeDoneView, PasswordResetView,
    PasswordResetDoneView, PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'
    ),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/form/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'),
        name='password_change_form'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'),
        name='password_change_done'
    ),
    path(
        'password_reset_form/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'password_reset_confirm/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'password_reset_complete/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complite.html'),
        name='password_reset_complete'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models


User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        verbose_name='Информация о группах',
        max_length=200
    )
    slug = models.SlugField(
        max_length=200, unique=True,
        db_index=True, verbose_name='slug'
    )
    description = models.TextField(
        verbose_name='Описание'
    )

    class Meta:
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        max_length=200, verbose_name='Текст',
    )
    pub_date = models.DateTimeField(
        auto_now_add=True, verbose_name='Дата'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group, blank=True, null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )
    

    class Meta:
        ordering = ('-pub_date',)
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:30]

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image',)
        help_texts = {
                'text': 'Новый текст поста',
                'group': 'Выберите группу, к которой будет относится пост'
            }
        labels = {
            'text': 'Текст поста',
            'group': 'Группа'
        }

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required

from .models import Group, Post, User
from .forms import PostForm
from .utils import get_pagin


def index(request):
    post_list = Post.objects.select_related('author', 'group')
    page_obj = get_pagin(post_list, request)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.select_related('author')
    page_obj = get_pagin(post_list, request)
    context = {
        'group': group,
        'page_obj': page_obj
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    user_posts = author.posts.select_related('group')
    page_obj = get_pagin(user_posts, request)
    context = {
        'author': author,
        'page_obj': page_obj
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    context = {
        'post': post,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    
    context = {
        'form': form
    }
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author)
    return render(request, 'posts/post_create.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post.pk)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post,
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post.pk)
    context = {
        'form': form,
        'post': post,
    }
    return render(request, 'posts/post_create.html', context)

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
<!-- templates/about/author.html -->
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h1>Привет, я автор</h1>
<p>
  Тут я размещу информацию о себе, используя свои умения верстать.
  Картинки, блоки, элементы бустрап. А может быть, просто напишу несколько абзацев текста. 
</p>
{% endblock %}

yatube/templates/about/tech.html
<!-- templates/about/tech.html -->
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
{% comment %} Колонки с отступом сверху и снизу {% endcomment %}
<div class="row">
  <h1>Вот что я умею</h1>
  {% comment %}
    Боковой блок со списком технологий 
    Займет всю ширину блока на мобильном
    и 25% при размерах экрана ≥768px
  {% endcomment %}
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  {% comment %}
    Статья  
    Займет всю ширину блока на мобильном
    и 75% при размерах экрана ≥768px
  {% endcomment %}
  <article class="col-12 col-md-9">
    <p>Текст страницы "Технологии"</p>
  </article>
</div>
{% endblock %}

yatube/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"
    <link rel="icon" href="{% static 'img/fav/fav.ico' type="image" %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>       
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
<p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/form_errors.html
{% if form.errors %}
  {% for field in form %} 
    {% for error in field.errors %}
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape}}
    </div>
  {% endfor %}
{% endif %}           

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" 
      class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube
    </a>
    {% with request.resolver_match.view_name as view_name %}
    <ul class="nav nav-pills">
      <li class="nav-item"> 
        <a class="nav-link {% if view_name == 'posts:index' %}active{% endif %}" 
          href="{% url 'posts:index' %}">Главная</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link {% if view_name == 'about:author' %}active{% endif %}" 
          href="{% url 'about:author' %}">Об авторе</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if view_name == 'about:tech' %}active{% endif %}"
          href="{% url 'about:tech' %}">Технологии</a>
      </li>
      {% if request.user.is_authenticated %}
      <li class="nav-item"> 
        <a class="nav-link {% if view_name == 'posts:post_create' %}active{% endif %}"
          href="{% url 'posts:post_create' %}">Новая запись</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light" href="{% url 'users:password_change_form' %}">Изменить пароль</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
      </li>
      <li>
       <a href="{% url 'posts:profile' user.username %}">Пользователь: {{ user.username }}</a>
      </li>
      {% else %}
      <li class="nav-item"> 
        <a class="nav-link link-light" href="{% url 'users:login' %}">Войти</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light" href="{% url 'users:signup' %}">Регистрация</a>
      </li>
      {% endif %}
    </ul>
    {% endwith %}
  </div>
</nav>

             

yatube/templates/includes/iter_form.html
{% load user_filters %}
{% for field in form %}
<div class="form-group row my-3"
{% if field.field.required %}
  aria-required="true"
{% else %}
  aria-required="false"
{% endif %}>
<label for="{{ field.id_for_label }}">
  {{ field.label }}
    {% if field.field.required %}
      <span class="required text-danger">*</span>
    {% endif %}
</label>
<div>
  {{ field|addclass:'form-control' }}
  {% if field.help_text %}
    <small id="{{ field.id_for_label }}-help" class="form-text-muted">
      {{ field.help_text|safe }}
    </small>
  {% endif %}
</div>
</div>  
{% endfor %}       

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %} Записи сообщества; {{ group }} {% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>
      <h4>Записи сообщества; {{ group.description|linebreaks }}</h4><hr>
    </p>
    {% for post in page_obj %}
      {% include 'posts/includes/post_card.html' with show_group_list=True %}  
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
    <hr>
  </div>  
{% endblock %} 

yatube/templates/posts/includes/paginator.html
{% load static %}
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/includes/post_card.html
{% load thumbnail %}
<article>
  <ul>
    <li>
      Автор: {{ post.author }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
    <li>
      Текст:
      <P>
        {{ post.text|linebreaksbr }}
      </p>
      {% thumbnail post.image "450x275" crop="center" as im %}
        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
      {% endthumbnail %} 
    </li>
    {% if not show_profile %}
      <li>        
        <a href="{% url 'posts:profile' post.author %}">Все посты пользователя</a>
      </li>
    {% endif %}
    <li>
      <a href="{% url 'posts:post_detail' post.id %}">Подробная информация</a>
    </li> 
      {% if post.group %}
        {% if not show_group_list %}
          <li>      
            <a href="{% url 'posts:group_list' post.group.slug %}">
              Все записи группы, {{ post.group.slug }}</a>
          </li>     
        {% endif %}
      {% endif %}
  </ul>
</article>

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
  <div class="container py-5">
    {% include 'posts/includes/paginator.html' %}
    <h2>Главная страница</h2>
    {% for post in page_obj %}
      {% include 'posts/includes/post_card.html' %}  
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
    <hr>
  </div> 
{% endblock %}

yatube/templates/posts/post_create.html
{% extends 'base.html' %} 
{% block title %} 
  {% if form.instance.pk %} 
    Редактор поста 
  {% else %} 
    Новый пост 
  {% endif %} 
{% endblock %}   
{% block content %} 
  <div class="container py-5"> 
    <div class="row justify-content-center"> 
      <div class="col-md-8 p-5"> 
        <div class="card"> 
          <div class="card-header"> 
            {% if form.instance.pk %}       
              Редактируемый пост 
            {% else %} 
              Новый пост 
            {% endif %}                  
          </div> 
          <div class="card-body"> 
            {% include 'includes/form_errors.html' %}         
            <form method="post" enctype="multipart/form-data" action="{% if form.instance.pk %}{% url 'posts:post_edit' form.instance.pk %} 
            {% else %}{% url 'posts:post_create' %}{% endif %}"> 
            {% csrf_token %}             
              {% include 'includes/iter_form.html' %} 
              <div class="d-flex justify-content-end"> 
                <button type="submit" class="btn btn-primary"> 
                  {% if form.instance.pk %} 
                    Сохранить 
                  {% else %} 
                    Добавить 
                  {% endif %}    
                </button> 
              </div> 
            </form> 
          </div> 
        </div> 
      </div> 
    </div> 
  </div>    
{% endblock %} 

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
{% load thumbnail %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }} 
        </li>
          {% if post.group %}
        <li class="list-group-item">
          Группа: {{ post.group }}
          <a href="{% url 'posts:group_list' post.group.slug %}">
            все записи группы
          {% else %}
            <span style='color: red'>Этой публикации нет ни в одном сообществе.</span>
          {% endif %}
          </a>
        </li>
        <li class="list-group-item">
          Автор: {{ post.author }},  id: {{ post.id }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ post.author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author %}">
            все посты пользователя
          </a>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:post_edit' post.id %}">
            Редактировать пост
          </a>
        </li>  
      </ul>
    </aside>
  <article class="col-12 col-md-9">
    <p>
      {{ post.text|linebreaksbr }}
    </p>
    {% thumbnail post.image "450x275" crop="center" as im %}
    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
    {% endthumbnail %}
    {% thumbnail post.image "450x275" crop="center" as im %}
    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
    {% endthumbnail %}
  </article>
  </div>        
{% endblock %}    

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}
  Профайл пользователя {{ user.username }}
{% endblock %}
{% block content %}
  <div class="container ru-5">   
    <h2>Все посты пользователя {{ author.get_full_name }}</h2>
      <h3>Всего постов: {{ author.posts.count }} </h3>
      {% for post in page_obj %}
      {% include 'posts/includes/post_card.html' with show_profile=True %}
      {% if not forloop.last %}<hr>{% endif %}
      {% endfor %} 
    {% include 'posts/includes/paginator.html' %}
  </div>  
{% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход 
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи Ждём вас снова!
        </p>
      </div>
    </div>
  </div>  
</div>  
{% endblock %}

yatube/templates/users/login.html
{% extends 'base.html' %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
         {% include 'includes/form_errors.html' %}
          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}>
          {% csrf_token %}
          {% include 'includes/iter_form.html' %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
              Забыли пороль?
            </a>
          </div>
          </form>
        </div>
      </div>  
    </div>
  </div>
{% endblock %}
                      

yatube/templates/users/password_change_done.html
{% extends 'base.html'%}
{% block title %}Пароль изменён{% endblock %}
{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Пароль изменён
        </div>
        <div class="card-body"> 
          <p>Пароль изменён успешно</p>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
</div>
{% endblock %}
      

yatube/templates/users/password_change_form.html
{% extends 'base.html' %}
{% block title %}Изменение пароля{% endblock %}
{% block content %} 
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Изменить пароль
        </div>
        <div class="card-body">
          <form method="post" action="{% url 'users:password_change_form' %}">
            {% csrf_token %}
            {% include 'includes/iter_form.html' %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Изменить пароль
              </button>
            </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
</div>
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Восстановление пароля завершено
        </div>
        <div class="card-body">
          <p>Ваш пароль был сохранен. Используйте его для входа</p>
          <a href="{% url 'users:login.html' %}">войти</a>
        </div> 
      </div> 
    </div>
  </div> 
</div>
{% endblock %}
      

yatube/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% block title %}Новый пароль{% endblock %}
{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Введите новый пароль
        </div>
        <div class="card-body">
          {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
          {% csrf_token %}
          {% include 'includes/iter_form.html' %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Назначить новый пароль
            </button>
          </div>  
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
  <!-- если использована неправильная ссылка -->
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Ошибка
        </div>
        <div class="card-body">
          <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
  <!-- конец если использована неправильная ссылка -->
</div>
{% endblock %}
      

yatube/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Отправлено письмо
        </div>
        <div class="card-body">
          <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
        </div> 
      </div> 
    </div>
  </div> 
</div>
{% endblock %}
      
    

yatube/templates/users/password_reset_form.html
{% extends 'base.html' %}
{% block title %}Сброс пароля{% endblock %}
{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
        </div>
        <div class="card-body"> 
          <form method="post" action="{% url 'users:password_reset_form' %}">
            {% csrf_token %}
            {% include 'includes/iter_form.html' %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Сбросить пароль
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>  
</div>
{% endblock %}     

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %} 
            {% include 'includes/form_errors.html' %}
            <form method="post" action="{% url 'users:signup' %}">
            {% csrf_token %}
            {% include 'includes/iter_form.html' %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Зарегистрироваться
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}